from .get_device_type import NODE_CLASS_MAPPINGS as GET_DEVICE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GET_DEVICE_DISPLAY_MAPPINGS
from .add_video_text_watermark import NODE_CLASS_MAPPINGS as TEXT_WATERMARK_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_WATERMARK_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(GET_DEVICE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TEXT_WATERMARK_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS.update(GET_DEVICE_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TEXT_WATERMARK_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

